app:
  name: "placeholder"
  addr: "placeholder"
  port: "placeholder"
  password_pepper: "placeholder"

db:
  user: "placeholder"
  password: "placeholder"
  dbname: "placeholder"
  addr: "placeholder"
  port: "placeholder"